package cn.zju.mapper;

import cn.zju.bean.OrderDetail;
import cn.zju.bean.OrderDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_detail
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int countByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_detail
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int deleteByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_detail
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_detail
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int insert(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_detail
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int insertSelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_detail
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    List<OrderDetail> selectByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_detail
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    OrderDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_detail
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") OrderDetail record, @Param("example") OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_detail
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int updateByExample(@Param("record") OrderDetail record, @Param("example") OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_detail
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int updateByPrimaryKeySelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_detail
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int updateByPrimaryKey(OrderDetail record);
}