package cn.zju.mapper;

import cn.zju.bean.ProductSku;
import cn.zju.bean.ProductSkuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductSkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_sku
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int countByExample(ProductSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_sku
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int deleteByExample(ProductSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_sku
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_sku
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int insert(ProductSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_sku
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int insertSelective(ProductSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_sku
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    List<ProductSku> selectByExample(ProductSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_sku
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    ProductSku selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_sku
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProductSku record, @Param("example") ProductSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_sku
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int updateByExample(@Param("record") ProductSku record, @Param("example") ProductSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_sku
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int updateByPrimaryKeySelective(ProductSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_sku
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int updateByPrimaryKey(ProductSku record);
}