package cn.zju.mapper;

import cn.zju.bean.ProductBrand;
import cn.zju.bean.ProductBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_brand
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int countByExample(ProductBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_brand
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int deleteByExample(ProductBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_brand
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_brand
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int insert(ProductBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_brand
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int insertSelective(ProductBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_brand
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    List<ProductBrand> selectByExample(ProductBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_brand
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    ProductBrand selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_brand
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProductBrand record, @Param("example") ProductBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_brand
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int updateByExample(@Param("record") ProductBrand record, @Param("example") ProductBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_brand
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int updateByPrimaryKeySelective(ProductBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_brand
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int updateByPrimaryKey(ProductBrand record);
}