package cn.zju.mapper;

import cn.zju.bean.Useryer;
import cn.zju.bean.UseryerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UseryerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_buyer
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int countByExample(UseryerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_buyer
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int deleteByExample(UseryerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_buyer
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_buyer
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int insert(Useryer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_buyer
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int insertSelective(Useryer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_buyer
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    List<Useryer> selectByExample(UseryerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_buyer
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    Useryer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_buyer
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") Useryer record, @Param("example") UseryerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_buyer
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int updateByExample(@Param("record") Useryer record, @Param("example") UseryerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_buyer
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int updateByPrimaryKeySelective(Useryer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_buyer
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    int updateByPrimaryKey(Useryer record);
}