package cn.zju.bean;

public class OrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_detail.id
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_detail.order_id
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_detail.product_id
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_detail.product_name
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_detail.color
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_detail.size
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    private String size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_detail.price
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_detail.amount
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    private Integer amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_detail.id
     *
     * @return the value of bbs_detail.id
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_detail.id
     *
     * @param id the value for bbs_detail.id
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_detail.order_id
     *
     * @return the value of bbs_detail.order_id
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_detail.order_id
     *
     * @param orderId the value for bbs_detail.order_id
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_detail.product_id
     *
     * @return the value of bbs_detail.product_id
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_detail.product_id
     *
     * @param productId the value for bbs_detail.product_id
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_detail.product_name
     *
     * @return the value of bbs_detail.product_name
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_detail.product_name
     *
     * @param productName the value for bbs_detail.product_name
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_detail.color
     *
     * @return the value of bbs_detail.color
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_detail.color
     *
     * @param color the value for bbs_detail.color
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_detail.size
     *
     * @return the value of bbs_detail.size
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_detail.size
     *
     * @param size the value for bbs_detail.size
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_detail.price
     *
     * @return the value of bbs_detail.price
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_detail.price
     *
     * @param price the value for bbs_detail.price
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_detail.amount
     *
     * @return the value of bbs_detail.amount
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_detail.amount
     *
     * @param amount the value for bbs_detail.amount
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
}