package cn.zju.bean;

public class ProductBrand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_brand.id
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_brand.name
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_brand.description
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_brand.img_url
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_brand.web_site
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    private String webSite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_brand.sort
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_brand.is_display
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    private Boolean isDisplay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_brand.id
     *
     * @return the value of bbs_brand.id
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_brand.id
     *
     * @param id the value for bbs_brand.id
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_brand.name
     *
     * @return the value of bbs_brand.name
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_brand.name
     *
     * @param name the value for bbs_brand.name
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_brand.description
     *
     * @return the value of bbs_brand.description
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_brand.description
     *
     * @param description the value for bbs_brand.description
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_brand.img_url
     *
     * @return the value of bbs_brand.img_url
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_brand.img_url
     *
     * @param imgUrl the value for bbs_brand.img_url
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_brand.web_site
     *
     * @return the value of bbs_brand.web_site
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public String getWebSite() {
        return webSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_brand.web_site
     *
     * @param webSite the value for bbs_brand.web_site
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public void setWebSite(String webSite) {
        this.webSite = webSite == null ? null : webSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_brand.sort
     *
     * @return the value of bbs_brand.sort
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_brand.sort
     *
     * @param sort the value for bbs_brand.sort
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_brand.is_display
     *
     * @return the value of bbs_brand.is_display
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public Boolean getIsDisplay() {
        return isDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_brand.is_display
     *
     * @param isDisplay the value for bbs_brand.is_display
     *
     * @mbggenerated Sun Apr 29 22:23:11 CST 2018
     */
    public void setIsDisplay(Boolean isDisplay) {
        this.isDisplay = isDisplay;
    }
}